// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtbJM83iLdc-NmRCxPNejf-WuWXZqe8ds',
    appId: '1:777887054216:web:eb7dbc3e8508443cb1e23d',
    messagingSenderId: '777887054216',
    projectId: 'ottomate-99c32',
    authDomain: 'ottomate-99c32.firebaseapp.com',
    storageBucket: 'ottomate-99c32.appspot.com',
    measurementId: 'G-R080RT9KEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYqX5_nTcs2zcvSmoCGJZy5LRVU6msdpU',
    appId: '1:777887054216:android:55449a2bacb7dca8b1e23d',
    messagingSenderId: '777887054216',
    projectId: 'ottomate-99c32',
    storageBucket: 'ottomate-99c32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQoy8TiEEnL2kGqNALTgchq7MJbOrJ78E',
    appId: '1:777887054216:ios:a3869fc0f29815e0b1e23d',
    messagingSenderId: '777887054216',
    projectId: 'ottomate-99c32',
    storageBucket: 'ottomate-99c32.appspot.com',
    iosClientId: '777887054216-bsscsaii6lbqlhe2vtge5n0mvbulfboh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ottomate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQoy8TiEEnL2kGqNALTgchq7MJbOrJ78E',
    appId: '1:777887054216:ios:674fe1b9985079d4b1e23d',
    messagingSenderId: '777887054216',
    projectId: 'ottomate-99c32',
    storageBucket: 'ottomate-99c32.appspot.com',
    iosClientId: '777887054216-i15746mpguo9trhiacpp59h69qvle6m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ottomate.RunnerTests',
  );
}
